name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install commit message convention lib
        run: npm i commitlint-config-wizardoc -D

      - name: Check commit message
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.yml

  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: rustfmt --check  # -- or --
      # - run: cargo fmt --all -- --check
